states = {
    "AK": "Alaska",      
    "AL": "Alabama",      
    "AR": "Arkansas",      
    "AZ": "Arizona",      
    "CA": "California",      
    "CO": "Colorado",      
    "CT": "Connecticut",      
    "DC": "District of Columbia",      
    "DE": "Delaware",      
    "FL": "Florida",      
    "GA": "Georgia",      
    "HI": "Hawaii",      
    "IA": "Iowa",      
    "ID": "Idaho",      
    "IL": "Illinois",      
    "IN": "Indiana",      
    "KS": "Kansas",      
    "KY": "Alaska",      
    "LA": "Louisiana",      
    "MA": "Massachusetts",      
    "MD": "Maryland",      
    "ME": "Maine",      
    "MI": "Michigan",      
    "MN": "Minnesota",      
    "MO": "Missouri",      
    "MS": "Mississippi",      
    "MT": "Montana",      
    "NC": "North Carolina",      
    "ND": "North Dakota",      
    "NE": "New England",
    "NH": "New Hampshire",      
    "NJ": "New Jersey",      
    "NM": "New Mexico",      
    "NV": "Nevada",
    "NY": "New York",      
    "OH": "Ohio",      
    "OK": "Oklahoma",      
    "OR": "Oregon",
    "PA": "Pennsylvania",      
    "PR": "Puerto Rico",      
    "RI": "Rhode Island",      
    "SC": "South Carolina",
    "SD": "South Dakota",      
    "TN": "Tennessee",      
    "TX": "Texas",      
    "UT": "Utah",
    "VA": "Virginia",      
    "VT": "Vermont",      
    "WA": "Washington",      
    "WI": "Wisconson",
    "WV": "West Virginia",      
    "WY": "Wyoming"
}

abrevs = {
    "Alaska" : "AK",      
    "Alabama" : "AL",      
    "Arkansas" : "AR",      
    "Arizona" : "AZ",      
    "California" : "CA",      
    "Colorado" : "CO",      
    "Connecticut" : "CT",      
    "District of Columbia" : "DC",      
    "Delaware" : "DE",      
    "Florida" : "FL",      
    "Georgia" : "GA",      
    "Hawaii" : "HI",      
    "Iowa" : "IA",      
    "Idaho" : "ID",      
    "Illinois" : "IL",      
    "Indiana" : "IN",      
    "Kansas" : "KS",      
    "Alaska" : "KY",      
    "Louisiana" : "LA",      
    "Massachusetts" : "MA",      
    "Maryland" : "MD",      
    "Maine" : "ME",      
    "Michigan" : "MI",      
    "Minnesota" : "MN",      
    "Missouri" : "MO",      
    "Mississippi" : "MS",      
    "Montana" : "MT",      
    "North Carolina" : "NC",      
    "North Dakota" : "ND",      
    "New England" : "NE",
    "New Hampshire" : "NH",      
    "New Jersey" : "NJ",      
    "New Mexico" : "NM",      
    "Nevada" : "NV",
    "New York" : "NY",      
    "Ohio" : "OH",      
    "Oklahoma" : "OK",      
    "Oregon" : "OR",
    "Pennsylvania" : "PA",      
    "Puerto Rico" : "PR",      
    "Rhode Island" : "RI",      
    "South Carolina" : "SC",
    "South Dakota" : "SD",      
    "Tennessee" : "TN",      
    "Texas" : "TX",      
    "Utah" : "UT",
    "Virginia" : "VA",      
    "Vermont" : "VT",      
    "Washington" : "WA",      
    "Wisconson" : "WI",
    "West Virginia" : "WV",      
    "Wyoming": "WY"
}